import { useEffect, useState } from 'react';
import DOMPurify from 'dompurify';
import { asString, asStringArray, getPageContent, type PageContent } from '@/lib/cms';

export default function About() {
  const [content, setContent] = useState<PageContent>({});
  useEffect(() => { void getPageContent('about').then(setContent); }, []);
  const hero = asString(content.hero_background, 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&q=80'); const background = asString(content.content_background, 'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&q=80');
  return <div className="pt-16 min-h-screen"><section className="relative py-20"><img src={hero} alt="Premium woodworking" className="absolute inset-0 w-full h-full object-cover" /><div className="absolute inset-0 bg-gray-900/70" /><h1 className="relative text-4xl md:text-5xl font-bold text-white text-center">{asString(content.hero_title, 'About Us')}</h1></section><section className="py-20 px-4 relative"><img src={background} alt="Woodworking craftsmanship" className="absolute inset-0 w-full h-full object-cover" /><div className="absolute inset-0 bg-white/85" /><article className="relative max-w-4xl mx-auto bg-white/90 rounded-2xl shadow-xl p-8 md:p-12"><h2 className="text-3xl font-semibold text-gray-900 mb-6">{asString(content.story_title, 'Our Story')}</h2><div className="prose prose-lg max-w-none text-gray-700" dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(asString(content.story_html, '<p>For over two decades, we have delivered exceptional quality and craftsmanship to homeowners, architects, and interior designers.</p><p>We source the finest materials, employ skilled craftsmen, and deliver projects that exceed expectations.</p>')) }} /><h3 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">{asString(content.values_title, 'Our Values')}</h3><ul className="list-disc pl-6 text-gray-700 space-y-2">{asStringArray(content.values, ['Unwavering commitment to quality', 'Transparent communication throughout the project', 'Innovation in design and execution', 'Sustainable practices and materials', 'Customer satisfaction above all']).map((value) => <li key={value}>{value}</li>)}</ul></article></section></div>;
}