import { useEffect, useState } from 'react';
import { motion, useAnimationControls } from 'framer-motion';
import { Award, ChevronDown, Clock, PenTool as Tool, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { asString, fallbackSettings, getPageContent, getSiteSettings, getVisibleTestimonials, type PageContent, type SiteSettings, type Testimonial } from '@/lib/cms';

const fallbackFeatures = [
  { icon: <Tool className="w-12 h-12" />, title: 'Premium Quality Interior Design', description: 'Expert interior designers in Ahmedabad delivering premium quality materials and craftsmanship' },
  { icon: <Clock className="w-12 h-12" />, title: 'Timely Project Delivery', description: 'On-time completion of interior projects across Ahmedabad with professional execution' },
  { icon: <Award className="w-12 h-12" />, title: 'Expert Interior Team', description: 'Skilled interior designers and craftsmen with years of experience in Ahmedabad' },
  { icon: <Users className="w-12 h-12" />, title: 'Customer-Focused Approach', description: 'Trusted interior design services in Ahmedabad with 100% customer satisfaction' },
];

function Testimonials({ rows }: { rows: Testimonial[] }) {
  const controls = useAnimationControls();
  const repeated = rows.length ? [...rows, ...rows, ...rows] : [];
  useEffect(() => { if (repeated.length) void controls.start({ x: [0, -(repeated.length * 350)], transition: { duration: 40, ease: 'linear', repeat: Infinity } }); }, [controls, repeated.length]);
  return <div onMouseEnter={() => controls.stop()} onMouseLeave={() => { if (repeated.length) void controls.start({ x: [0, -(repeated.length * 350)], transition: { duration: 40, ease: 'linear', repeat: Infinity } }); }}><div className="overflow-hidden"><motion.div animate={controls} className="flex gap-6" style={{ minWidth: 'max-content' }}>{repeated.map((row, index) => <div key={`${row.id}-${index}`} className="bg-white/10 backdrop-blur-sm p-8 rounded-2xl w-[320px] shrink-0"><div className="flex items-center mb-6"><div className="w-16 h-16 rounded-full bg-primary/30 flex items-center justify-center text-white text-xl font-bold mr-4">{row.name.charAt(0)}</div><div><h3 className="text-xl font-semibold text-white">{row.name}</h3><p className="text-gray-300">{row.role}</p></div></div><p className="text-gray-100 italic">{row.quote}</p></div>)}</motion.div></div></div>;
}

export default function Home() {
  const [content, setContent] = useState<PageContent>({});
  const [settings, setSettings] = useState<SiteSettings>(fallbackSettings);
  const [testimonials, setTestimonials] = useState<Testimonial[]>([]);
  useEffect(() => { void Promise.all([getPageContent('home'), getSiteSettings(), getVisibleTestimonials()]).then(([page, site, rows]) => { setContent(page); setSettings(site); setTestimonials(rows); }); }, []);
  const poster = asString(content.hero_poster, 'https://images.unsplash.com/photo-1588854337115-1c67d9247e4d?auto=format&fit=crop&q=80&w=2000');
  const heroVideo = asString(content.hero_video);
  const whyBackground = asString(content.why_background, 'https://images.unsplash.com/photo-1615876234886-fd9a39fda97f?auto=format&fit=crop&q=80&w=2000');
  const testimonialsBackground = asString(content.testimonials_background, 'https://images.unsplash.com/photo-1564069114553-7215e1ff1890?auto=format&fit=crop&q=80&w=2000');
  return <div className="min-h-screen"><section className="relative h-screen"><div className="absolute inset-0 overflow-hidden">{heroVideo ? <video autoPlay loop muted playsInline poster={poster} className="w-full h-full object-cover"><source src={heroVideo} type="video/mp4" /></video> : <img src={poster} alt="Interior design" className="w-full h-full object-cover" />}<div className="absolute inset-0 bg-gray-900/60" /></div><div className="relative h-full flex flex-col items-center justify-center text-white px-4 text-center"><motion.h1 initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-4xl md:text-6xl font-bold mb-6">{asString(content.hero_title, 'From Concept to Creation')}</motion.h1><motion.p initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-xl md:text-2xl mb-8 max-w-2xl">{asString(content.hero_subtitle, 'Premium Plywood, Hardware & Expert Interior Construction Turnkey Solutions')}</motion.p><div className="flex flex-wrap justify-center gap-4"><a href={`https://wa.me/${settings.whatsapp_number.replace(/[^\d]/g, '')}`} target="_blank" rel="noreferrer" className="bg-primary hover:bg-primary-dark text-white px-8 py-3 rounded-full text-lg font-semibold">Get a Quote</a><Link to="/services" className="bg-white/10 hover:bg-white/20 text-white px-8 py-3 rounded-full text-lg font-semibold">Explore Services</Link></div></div><ChevronDown className="absolute bottom-8 left-1/2 -translate-x-1/2 text-white w-8 h-8 animate-bounce" /></section><section className="py-20 px-4 relative"><img src={whyBackground} alt="Woodworking craftsmanship" className="absolute inset-0 w-full h-full object-cover" /><div className="absolute inset-0 bg-white/85" /><div className="max-w-7xl mx-auto relative"><div className="text-center mb-16"><h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">{asString(content.why_title, 'Why Choose Us')}</h2><p className="text-gray-600 max-w-2xl mx-auto">{asString(content.why_subtitle, 'We deliver excellence in every aspect of our work, from materials to execution')}</p></div><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">{fallbackFeatures.map((feature) => <div key={feature.title} className="bg-white/90 p-6 rounded-2xl shadow-lg"><div className="text-primary mb-4">{feature.icon}</div><h3 className="text-xl font-semibold mb-3">{feature.title}</h3><p className="text-gray-600">{feature.description}</p></div>)}</div></div></section><section className="py-20 px-4 relative"><img src={testimonialsBackground} alt="Interior workshop" className="absolute inset-0 w-full h-full object-cover" /><div className="absolute inset-0 bg-gray-900/80" /><div className="max-w-7xl mx-auto relative"><h2 className="text-3xl md:text-4xl font-bold text-center mb-16 text-white">{asString(content.testimonials_title, 'What Our Clients Say')}</h2><Testimonials rows={testimonials} /></div></section></div>;
}