import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';
import { asString, getPageContent, getVisibleProjects, type PageContent, type Project } from '@/lib/cms';

export default function Projects() {
  const [content, setContent] = useState<PageContent>({}); const [rows, setRows] = useState<Project[]>([]);
  useEffect(() => { void Promise.all([getPageContent('projects'), getVisibleProjects()]).then(([page, projects]) => { setContent(page); setRows(projects); }); }, []);
  const hero = asString(content.hero_background, 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=2000&q=80'); const background = asString(content.grid_background, 'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=2000&q=80');
  return <div className="pt-16 min-h-screen"><section className="relative py-20"><img src={hero} alt="Luxury home design" className="absolute inset-0 w-full h-full object-cover" /><div className="absolute inset-0 bg-gray-900/70" /><div className="relative text-center text-white"><h1 className="text-4xl md:text-5xl font-bold mb-6">{asString(content.hero_title, 'Our Projects')}</h1><p className="text-xl text-gray-200 max-w-2xl mx-auto">{asString(content.hero_subtitle, 'Explore our portfolio of premium woodworking and interior projects')}</p></div></section><section className="py-20 px-4 relative"><img src={background} alt="Woodworking background" className="absolute inset-0 w-full h-full object-cover" /><div className="absolute inset-0 bg-white/90" /><div className="relative max-w-7xl mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">{rows.map((project) => <article key={project.id} className="group relative aspect-square overflow-hidden rounded-xl shadow-lg"><img src={project.cover_image_url ?? background} alt={project.title} className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/30 to-transparent flex items-end"><div className="p-6 text-white"><p className="text-sm text-primary-200 mb-2">{project.category}</p><h2 className="text-xl font-bold mb-2">{project.title}</h2><p className="text-sm text-gray-200 line-clamp-2 mb-4">{project.description}</p><Link to={`/projects/${project.slug}`} className="inline-flex items-center">View Project <ArrowRight className="ml-2 w-4 h-4" /></Link></div></div></article>)}</div></section></div>;
}