import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Calendar, MapPin, Tag } from 'lucide-react';
import { galleryItems, getVisibleProjects, type Project } from '@/lib/cms';
import Breadcrumbs from '@/components/Breadcrumbs';
import { SEO_BASE_URL, createBreadcrumbSchema } from '@/lib/seo-content';
import { usePageSeo } from '@/lib/seo';

export default function ProjectDetail() {
  const { id } = useParams(); const [project, setProject] = useState<Project | null>(null); const [loaded, setLoaded] = useState(false);
  const projectPath = `/projects/${encodeURIComponent(id ?? '')}`;
  const description = project?.description || `Explore ${project?.title ?? 'this'} interior project by ABP Interior in Ahmedabad.`;
  const projectSchema = project ? { '@context': 'https://schema.org', '@graph': [createBreadcrumbSchema([{ name: 'Home', path: '/' }, { name: 'Projects', path: '/projects' }, { name: project.title, path: projectPath }]), { '@type': 'CreativeWork', name: project.title, description, ...(project.cover_image_url ? { image: project.cover_image_url } : {}), about: project.category, ...(project.location ? { contentLocation: { '@type': 'Place', name: project.location } } : {}) }] } : null;
  usePageSeo({ title: project ? `${project.title} | ${project.category} in Ahmedabad | ABP Interior` : 'Interior project | ABP Interior', description, path: projectPath, robots: project ? 'index, follow' : loaded ? 'noindex, follow' : 'index, follow', image: project?.cover_image_url, structuredData: projectSchema });
  useEffect(() => { void getVisibleProjects().then((rows) => { setProject(rows.find((row) => row.slug === id) ?? null); setLoaded(true); }); }, [id]);
  if (!loaded) return <div className="pt-24 min-h-screen text-center">Loading project…</div>;
  if (!project) return <div className="pt-24 min-h-screen text-center"><h1 className="text-2xl font-bold">Project not found</h1><Link to="/projects" className="text-primary mt-4 inline-block">Return to Projects</Link></div>;
  const gallery = galleryItems(project.gallery); const images = gallery.length ? gallery : [{ url: project.cover_image_url ?? '', caption: project.title }]; const features = Array.isArray(project.features) ? project.features.filter((item): item is string => typeof item === 'string') : [];
  return <div className="pt-16 min-h-screen bg-gray-50"><Breadcrumbs items={[{ label: 'Home', path: '/' }, { label: 'Projects', path: '/projects' }, { label: project.title }]} /><section className="relative h-[60vh]"><img fetchPriority="high" src={images[0].url} alt={project.title} className="absolute inset-0 w-full h-full object-cover" /><div className="absolute inset-0 bg-gray-900/60" /><div className="relative h-full flex items-end"><div className="container mx-auto px-4 pb-16 text-white"><Link to="/projects" className="inline-flex items-center mb-6"><ArrowLeft className="w-5 h-5 mr-2" />Back to Projects</Link><h1 className="text-4xl md:text-5xl font-bold mb-4">{project.title}</h1><div className="flex flex-wrap gap-4"><span className="flex items-center"><MapPin className="w-5 h-5 mr-2" />{project.location}</span><span className="flex items-center"><Calendar className="w-5 h-5 mr-2" />{project.project_date}</span><span className="flex items-center"><Tag className="w-5 h-5 mr-2" />{project.category}</span></div></div></div></section><section className="container mx-auto px-4 py-16 max-w-5xl"><p className="text-xl text-gray-600 mb-8">{project.description}</p><h2 className="text-2xl font-bold mb-4">Key Features</h2><ul className="grid md:grid-cols-2 gap-4 mb-8">{features.map((feature) => <li key={feature} className="flex items-center text-gray-600"><span className="w-2 h-2 bg-primary rounded-full mr-2" />{feature}</li>)}</ul><h2 className="text-2xl font-bold mb-4">The Challenge</h2><p className="text-gray-600 mb-8">{project.challenge}</p><h2 className="text-2xl font-bold mb-4">Our Solution</h2><p className="text-gray-600 mb-12">{project.solution}</p><div className="grid md:grid-cols-2 gap-8">{images.map((image, index) => <figure key={`${image.url}-${index}`} className="relative aspect-square rounded-2xl overflow-hidden shadow-lg"><img loading="lazy" src={image.url} alt={image.caption ?? project.title} className="w-full h-full object-cover" /><figcaption className="absolute bottom-0 inset-x-0 p-4 text-white bg-gradient-to-t from-black/70 to-transparent">{image.caption}</figcaption></figure>)}</div></section></div>;
}