import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { HardHat, Hammer, Home, Package, PenTool, Ruler, ArrowRight, type LucideIcon } from 'lucide-react';
import { asString, fallbackSettings, getPageContent, getSiteSettings, getVisibleServices, type PageContent, type Service, type SiteSettings, whatsappUrl } from '@/lib/cms';
import Breadcrumbs from '@/components/Breadcrumbs';
import { publicPageSeo, createBreadcrumbSchema } from '@/lib/seo-content';
import { usePageSeo } from '@/lib/seo';

const icons: Record<string, LucideIcon> = { Package, Hammer, Home, PenTool, Ruler, HardHat };
const fallback = 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&q=80';

export default function Services() {
  usePageSeo({ ...publicPageSeo[1], path: '/services', structuredData: createBreadcrumbSchema([{ name: 'Home', path: '/' }, { name: 'Services', path: '/services' }]) });
  const [content, setContent] = useState<PageContent>({}); const [rows, setRows] = useState<Service[]>([]); const [settings, setSettings] = useState<SiteSettings>(fallbackSettings);
  useEffect(() => { void Promise.all([getPageContent('services'), getVisibleServices(), getSiteSettings()]).then(([page, services, site]) => { setContent(page); setRows(services); setSettings(site); }); }, []);
  const background = asString(content.hero_background, fallback); const gridBackground = asString(content.grid_background, 'https://images.unsplash.com/photo-1615876234886-fd9a39fda97f?auto=format&fit=crop&q=80'); const ctaBackground = asString(content.cta_background, 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=80');
  return <div className="pt-16 min-h-screen"><Breadcrumbs items={[{ label: 'Home', path: '/' }, { label: 'Services' }]} /><section className="relative py-20"><img loading="eager" fetchPriority="high" src={background} alt="Carpentry workshop" className="absolute inset-0 w-full h-full object-cover" /><div className="absolute inset-0 bg-gray-900/70" /><div className="relative text-center text-white"><h1 className="text-4xl md:text-5xl font-bold mb-6">{asString(content.hero_title, 'Our Services')}</h1><p className="text-xl text-gray-200 max-w-2xl mx-auto">{asString(content.hero_subtitle, 'Comprehensive solutions for all your plywood, hardware, and construction needs')}</p></div></section><section className="py-20 px-4 relative"><img loading="lazy" src={gridBackground} alt="Woodworking workshop" className="absolute inset-0 w-full h-full object-cover" /><div className="absolute inset-0 bg-white/90" /><div className="max-w-7xl mx-auto relative grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">{rows.map((service) => { const Icon = icons[service.icon_name] ?? Package; return <motion.article key={service.id} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="bg-white/90 p-8 rounded-2xl shadow-lg"><div className="text-primary mb-6"><Icon className="w-12 h-12" /></div><h2 className="text-2xl font-semibold mb-4">{service.title}</h2><p className="text-gray-600 mb-6">{service.description}</p><a href={service.cta_url ?? whatsappUrl(settings.whatsapp_number)} target="_blank" rel="noreferrer" className="inline-flex items-center text-primary font-semibold">{service.cta_label}<ArrowRight className="ml-2 w-4 h-4" /></a></motion.article>; })}</div></section><section className="relative py-16"><img loading="lazy" src={ctaBackground} alt="Interior project" className="absolute inset-0 w-full h-full object-cover" /><div className="absolute inset-0 bg-primary/90" /><div className="relative text-center text-white"><h2 className="text-3xl font-bold mb-8">{asString(content.cta_title, 'Ready to Start Your Project?')}</h2><a href={whatsappUrl(settings.whatsapp_number)} target="_blank" rel="noreferrer" className="inline-block bg-white text-primary px-8 py-3 rounded-full text-lg font-semibold">Contact Us Today</a></div></section></div>;
}