INSERT INTO public.site_settings (singleton, business_name, phone, whatsapp_number, email, address, social_links)
VALUES (true, 'ABP Interior', '+91 9377640080', '+919377640080', 'arvindpatel5862@gmail.com', 'G19 Satva Elegance, Silverstar Char Rasta, Chandlodiya, Ahmedabad, Gujarat', '{"instagram":"","facebook":"","linkedin":""}'::jsonb)
ON CONFLICT (singleton) DO UPDATE SET business_name = EXCLUDED.business_name, phone = EXCLUDED.phone, whatsapp_number = EXCLUDED.whatsapp_number, email = EXCLUDED.email, address = EXCLUDED.address, social_links = EXCLUDED.social_links;

INSERT INTO public.services (title, description, icon_name, cta_label, cta_url, sort_order, is_visible)
VALUES
('Premium Plywood & Laminates in Ahmedabad','Extensive collection of premium quality plywood and laminates in Ahmedabad. Best prices and genuine products for all interior requirements.','Package','Get Quote','https://wa.me/+919377640080',1,true),
('Hardware Solutions in Ahmedabad','Complete range of premium hardware, tools, and fittings from top brands. Visit our hardware store in Ahmedabad for quality products.','Hammer','Get Quote','https://wa.me/+919377640080',2,true),
('Modular Interior Solutions','Custom modular furniture and interior solutions in Ahmedabad. Expert designers for your home and office interiors.','Home','Get Quote','https://wa.me/+919377640080',3,true),
('Interior Design Services','Professional interior design services in Ahmedabad. Complete execution from concept to creation with premium finishing.','PenTool','Get Quote','https://wa.me/+919377640080',4,true),
('Architectural Planning','Expert architectural design and planning services in Ahmedabad. Comprehensive interior solutions for residential and commercial spaces.','Ruler','Get Quote','https://wa.me/+919377640080',5,true),
('Project Management','Professional interior project management and supervision in Ahmedabad. Ensuring quality and timely completion.','HardHat','Get Quote','https://wa.me/+919377640080',6,true)
ON CONFLICT DO NOTHING;

INSERT INTO public.projects (slug,title,category,location,project_date,description,challenge,solution,cover_image_url,gallery,features,sort_order,is_visible)
VALUES
('modern-villa','Modern Apartment Interior','Residential','Ahmedabad','July 2024','A contemporary apartment featuring custom plywood furniture, premium hardware fittings, and modern design elements. This project showcases our expertise in creating luxurious living spaces.','The main challenge was maximizing space utilization while maintaining a luxurious feel.','We implemented a sophisticated design approach using premium materials and smart space planning.','https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80','[{"url":"https://images.unsplash.com/photo-1600607687644-c7171b42498f?auto=format&fit=crop&w=1200&q=80","caption":"Master Bedroom with Custom Headboard"},{"url":"https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80","caption":"Modern Kitchen Design"}]'::jsonb,'["Custom plywood furniture with premium finishes","LED strip lighting and recessed spotlights","Built-in storage solutions","Premium finishes"]'::jsonb,1,true),
('bungalow-makeover','Bungalow Makeover','Residential','Ahmedabad','August 2024','A complete bungalow transformation with modern furniture, comfortable gathering areas, and smart storage ideas.','The challenge was balancing open entertaining areas with private spaces.','We created a flexible layout with movable furniture and carefully planned acoustic separation.','https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80','[{"url":"https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1200&q=80","caption":"Elegant Bedroom"},{"url":"https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80","caption":"Modular Kitchen"}]'::jsonb,'["Custom workstations with cable management","Premium storage solutions","LED lighting systems","Smart space utilization"]'::jsonb,2,true),
('luxury-apartment','Luxury Apartment Renovation','Residential','Ahmedabad','September 2024','A high-end apartment renovation showcasing premium materials, custom cabinetry, and sophisticated design elements.','Integrating modern amenities while preserving the classic architectural elements of the space.','We blended contemporary design with traditional elements using high-end materials and custom furniture.','https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1200&q=80','[{"url":"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80","caption":"Grand Living Room"},{"url":"https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=80","caption":"Master Suite"}]'::jsonb,'["Custom millwork throughout","Smart home integration","Premium stone surfaces","Luxury finishes"]'::jsonb,3,true),
('modern-design-villa','Latest Attractive Design Villa','Residential','Ahmedabad','October 2024','An elegant villa interior featuring custom woodwork, ambient bedrooms and bathrooms, and a sophisticated dining space.','The difficulty was giving each room a distinct style while keeping one cohesive villa experience.','Custom woodwork and lighting create a special mood in each room while shared details maintain flow.','https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80','[{"url":"https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1200&q=80","caption":"Grand Bedroom"},{"url":"https://images.unsplash.com/photo-1615876234886-fd9a39fda97f?auto=format&fit=crop&w=1200&q=80","caption":"Elegant Interior"}]'::jsonb,'["Custom wood paneling","Ambient lighting design","Premium seating solutions","Designer furniture"]'::jsonb,4,true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.testimonials (name,role,quote,rating,image_url,sort_order,is_visible)
VALUES
('Sandip Patel','Homeowner in Ahmedabad','Best interior designers in Ahmedabad! The quality of their plywood and workmanship is outstanding. Highly recommended for turnkey interior solutions!',5,NULL,1,true),
('Anjali Jain','Homeowner in Ahmedabad','Top interior design experts in Ahmedabad who used premium materials and made our interiors amazing without any fuss.',5,NULL,2,true),
('Rahul Jani','Homeowner in Ahmedabad','Excellent interior construction services in Ahmedabad. Everything from plywood selection to final execution was handled professionally!',5,NULL,3,true)
ON CONFLICT DO NOTHING;

INSERT INTO public.page_content (page_key, content)
VALUES
('home','{"hero_title":"From Concept to Creation","hero_subtitle":"Premium Plywood, Hardware & Expert Interior Construction Turnkey Solutions","hero_poster":"https://images.unsplash.com/photo-1588854337115-1c67d9247e4d?auto=format&fit=crop&q=80&w=2000","hero_video":"","why_title":"Why Choose Us","why_subtitle":"We deliver excellence in every aspect of our work, from materials to execution","why_background":"https://images.unsplash.com/photo-1615876234886-fd9a39fda97f?auto=format&fit=crop&q=80&w=2000","testimonials_title":"What Our Clients Say","testimonials_background":"https://images.unsplash.com/photo-1564069114553-7215e1ff1890?auto=format&fit=crop&q=80&w=2000"}'::jsonb),
('services','{"hero_title":"Our Services","hero_subtitle":"Comprehensive solutions for all your plywood, hardware, and construction needs","hero_background":"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&q=80","grid_background":"https://images.unsplash.com/photo-1615876234886-fd9a39fda97f?auto=format&fit=crop&q=80","cta_title":"Ready to Start Your Project?","cta_background":"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=80"}'::jsonb),
('projects','{"hero_title":"Our Projects","hero_subtitle":"Explore our portfolio of premium woodworking and interior projects","hero_background":"https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=2000&q=80","grid_background":"https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=2000&q=80"}'::jsonb),
('about','{"hero_title":"About Us","hero_background":"https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&q=80","content_background":"https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&q=80","story_title":"Our Story","story_html":"<p>For over two decades, we have been at the forefront of the woodworking and construction industry, delivering exceptional quality and craftsmanship to our clients.</p><p>We source the finest materials, employ skilled craftsmen, and deliver projects that exceed expectations.</p>","values_title":"Our Values","values":["Unwavering commitment to quality","Transparent communication throughout the project","Innovation in design and execution","Sustainable practices and materials","Customer satisfaction above all"]}'::jsonb),
('contact','{"hero_title":"Contact Us","hero_background":"https://images.unsplash.com/photo-1600607687644-c7171b42498f?auto=format&fit=crop&q=80","content_background":"https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&q=80","form_title":"Tell us about your project","success_message":"Thanks for reaching out. We will get back to you soon."}'::jsonb)
ON CONFLICT (page_key) DO NOTHING;